# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
     
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20'
 
    - name: setup screen
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      
    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Build Wasm
      run: make wasm

    - name: Store wasm artefact
      uses: actions/upload-artifact@v4
      with:
        name: froggo.wasm 
        path: froggo.wasm
